[agent]
  interval = "1s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "1s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false

[[outputs.influxdb_v2]]
  urls = ["http://127.0.0.1:8181"]
  token = "apiv3_X-YcH5CWvEYkkjDXILY0qhmm9W5jJR0FCgsxWOY_Z4EdHBvGNfiHBIu8fDZU7uujJ87ehrZTlSFLHWJuBxAUCQ"
  organization = "my-org"
  bucket = "wind_tunnel_test"

[[inputs.socket_listener]]
  service_address = "udp://:8094"
  data_format = "binary"
  endianness = "le"
  fieldexclude = ["packet_counter"]

  [[inputs.socket_listener.binary]]
    metric_name = "socket_listener"

    [[inputs.socket_listener.binary.entries]]
    name = "packet_counter"
    type = "uint32"
    assignment = "field"

    [[inputs.socket_listener.binary.entries]]
    name = "velocity"
    type = "float32"
    assignment = "field"

    [[inputs.socket_listener.binary.entries]]
    name = "alpha"
    type = "float32"
    assignment = "field"

    [[inputs.socket_listener.binary.entries]]
    name = "lift"
    type = "float32"
    assignment = "field"

    [[inputs.socket_listener.binary.entries]]
    name = "run_id"
    type = "string"
    assignment = "tag"
      bits = 160

    [[inputs.socket_listener.binary.entries]]
    name = "test_point"
    type = "string"
    assignment = "tag"
      bits = 80

