%% Simple InfluxDB 3 Core Test

clear;
clc;

%% Config

host = 'http://localhost:8181';

token = 'apiv3_X-YcH5CWvEYkkjDXILY0qhmm9W5jJR0FCgsxWOY_Z4EdHBvGNfiHBIu8fDZU7uujJ87ehrZTlSFLHWJuBxAUCQ';

bucket = 'matlab_data';

org = 'my-org';

%% Generate fake data

value = rand();

timestamp_ns = int64(posixtime(datetime('now')) * 1e9);

line = sprintf( ...
    'test_signal,sensor=matlab value=%f %d', ...
    value, ...
    timestamp_ns);

%% Write data

fprintf('Writing data...\n');

writeUrl = sprintf( ...
    '%s/api/v2/write?bucket=%s&org=%s&precision=ns', ...
    host, ...
    bucket, ...
    org);

options = weboptions( ...
    'HeaderFields', { ...
    'Authorization', ['Token ' token] ...
    }, ...
    'RequestMethod', 'post', ...
    'ContentType', 'text', ...
    'Timeout', 10);

webwrite(writeUrl, line, options);

fprintf('Write successful!\n');

pause(1);

%% Query data

fprintf('Running query...\n');

queryUrl = sprintf( ...
    '%s/api/v3/query_sql?format=json', ...
    host);

queryBody = struct;

queryBody.db = bucket;

queryBody.q = ...
    'SELECT * FROM test_signal ORDER BY time DESC LIMIT 5';

queryOptions = weboptions( ...
    'HeaderFields', { ...
    'Authorization', ['Token ' token] ...
    }, ...
    'MediaType', 'application/json', ...
    'RequestMethod', 'post', ...
    'Timeout', 10);

result = webwrite( ...
    queryUrl, ...
    queryBody, ...
    queryOptions);

fprintf('Query successful!\n');

disp(result);